
package:
    name: pygpu
    version: 2016.4.1

source:
    git_url: git@github.com:Theano/libgpuarray.git
    git_rev: c59a170
build:
    number: 1

requirements:
    build:
        - python
        - numpy
        - mako
        - cython
        - six
        - nose
        - cloog
        - cmake

    run:
        - python
        - numpy
        - mako
        - cython
        - six
        - nose
        - cloog
        - cmake

test:
    imports:
        - pygpu

about:
    home: https://github.com/Theano/libgpuarray/blob/master/LICENSE
    license: MIT
