
package:
    name: pygpu
    version: 2016.7.15

source:
    # git_url: git@github.com:Theano/libgpuarray.git
    git_url: git@github.com:trungnt13/libgpuarray.git
    git_rev: d9c5ed4
build:
    number: 1

requirements:
    build:
        - python
        - scipy ==0.17.1
        - numpy ==1.10.4
        - mako
        - cython
        - six
        - nose
        - cloog ==0.18.0
        - mpc ==1.0.3
        - mkl ==11.3.3

    run:
        - python
        - numpy
        - mako
        - cython
        - six
        - nose

# test:
#     imports:
#         - pygpu

about:
    home: https://github.com/Theano/libgpuarray/blob/master/LICENSE
    license: MIT
