
package:
    name: pygpu
    version: 2016.7.2

source:
    # git_url: git@github.com:Theano/libgpuarray.git
    git_url: git@github.com:trungnt13/libgpuarray.git
    git_rev: 09f6818
build:
    number: 1

requirements:
    build:
        - python
        - numpy
        - mako
        - cython
        - six
        - nose
        - cloog ==0.18.0
        - mpc ==1.0.3
        # - libcheck ==0.10.0

    run:
        - python
        - numpy
        - mako
        - cython
        - six
        - nose

test:
    imports:
        - pygpu

about:
    home: https://github.com/Theano/libgpuarray/blob/master/LICENSE
    license: MIT
