package:
  name: tcl
  version: 8.6b3

source:
  fn: tcl8.6b3-src.tar.gz
  url: ftp://ftp.tcl.tk/pub/tcl/tcl8_6/tcl8.6b3-src.tar.gz

requirements:
  build:
   - python

  run:
   - python

about:
  home: https://www.tcl.tk/software/tcltk/license.html
  license: Tcl/Tk License
