# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

package:
  name: gobject-introspection
  version: 1.46.0

source:
  fn: gobject-introspection-1.46.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.46/gobject-introspection-1.46.0.tar.xz
  sha256: 6658bd3c2b8813eb3e2511ee153238d09ace9d309e4574af27443d87423e4233

build:
  number: 1
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    # - cairo-gobject
    # - gettext #[osx]
    # - libffi32
    - glib
    - python
  run:
    # - libffi32
    - glib

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL
