package:
  name: picklable_itertools
  version: "0.1.1"

source:
  git_url: git@github.com:mila-udem/picklable-itertools.git
  git_rev: e002388

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - picklable_itertools

about:
  home: https://github.com/mila-udem/picklable-itertools
  license: MIT License
  summary: 'picklable-itertools'
