package:
  name: memory_profiler
  version: !!str 0.41

source:
  fn: memory_profiler-0.41.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.41.tar.gz
  md5: 8615aecbcc5cf1a761c819b9f4976cad

requirements:
  build:
    - python
    - pip

  run:
    - python

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: A module for monitoring memory usage of a python program
