# Copyright 2014-2015 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

# Based on the configure script output, we could potentially depend on cairo
# and (on Linux) fontconfig to get some extra features, but they are not
# needed for the desired functionality.

package:
  name: harfbuzz
  version: 1.0.6

source:
  fn: harfbuzz-1.0.6.tar.bz2
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.0.6.tar.bz2
  sha256: f616a7fbdc78a627043f9029000bf08c0c71df59cde4143fc92a014f6a993b26

build:
  number: 2
  detect_binary_files_with_prefix: true
  script_env:
    - NJOBS

requirements:
  build:
    - freetype
    - glib
    - gobject-introspection
    - icu
    - python # for gobject-introspection
  run:
    - freetype
    - glib
    - gobject-introspection
    - icu

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
  license: MIT
  summary: An OpenType text shaping engine.
