about: {home: 'http://www-lium.univ-lemans.fr/sidekit/', license:  LGPL License, summary: 'Open source package for Speaker and Language recognition.'}
package:
  name: sidekit
  version: "1.0.1"
requirements:
  build:
    - python
    - pip
    - mock >=1.0.1
    - nose >=1.3.4
    - numpy >=1.9.0
    - pyparsing >=2.0.2
    - python-dateutil >=2.2
    - scipy >=0.12.1
    - six >=1.8.0
    - wsgiref >=0.1.2
    - matplotlib >=1.3.1
  run:
    - python
    - mock >=1.0.1
    - nose >=1.3.4
    - numpy >=1.9.0
    - pyparsing >=2.0.2
    - python-dateutil >=2.2
    - scipy >=0.12.1
    - six >=1.8.0
    - wsgiref >=0.1.2
    - matplotlib >=1.3.1
source:
  url: ''
  md5: ''
test:
  commands: []
  files: []
  imports: []
  requires: []
